### ISSUE TITLE
Cannot copy friend toxID

### ISSUE THREAD

**Issue by PKEv** [irungentoo/toxcore#1300] opened 2015-03-22 20:25 UTC
Cannot copy friend's toxID and share it to another friend (cannot get saved nospam)

**Comment by zetok** [comment] 2015-03-26 08:44
It's not an issue. It's an expected behaviour and is not going to change. If that's all, please close issue.

**Comment by PKEv** [comment] 2015-03-26 20:32
The user can record the data, but can not read written ...
Is not that a bug?

**Comment by zetok** [comment] 2015-03-26 20:34
What data?

**Comment by PKEv** [comment] 2015-03-26 20:43
in this case the full ID

**Comment by zetok** [comment] 2015-03-26 20:43
But client doesn't have Tox ID?

**Comment by PKEv** [comment] 2015-03-26 20:46
friend's full ID
i must know it  to add friend, but i can't get it back

**Comment by zetok** [comment] 2015-03-26 20:48
Yes, since core doesn't supply that info, and is not going to.

I suggest you to read https://libtoxcore.so/core_concepts.html#the-tox-id

**Comment by PKEv** [comment] 2015-03-26 20:58
Yes, I understand it all
but if the user has in my friends, I should be able to get the tox-id

if you need this protection: logical after removing friend automatically change the value nospam

**Comment by zetok** [comment] 2015-03-27 05:02
>I should be able to get the tox-id

Why?

>logical after removing friend automatically change the value nospam

Why would you want to automatically break Tox ID?

**Comment by PKEv** [comment] 2015-03-27 07:41
Why?
Why I can record the data, but can not read written?

**Comment by PKEv** [comment] 2015-03-27 07:42
Why would you want to automatically break Tox ID?
If you're so afraid of spammers, it is much more effective way.

**Comment by vincenttschanz** [comment] 2015-05-15 14:25
Sorry I'm jumping on the bandwagon here, are you discussing about letting the user send a contact to another contact? 

I reported this feature request to the Antox dev, and he told me it was a toxcore limitation.

**Comment by linux-modder** [comment] 2015-05-15 14:46
It's not a limitation persay its a security feature to NOT be able to


Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: <https://www.plus.google.com/+CoreySheldon>
LinkedIn: <https://www.linkedin.com/profile/view?id=70127804>
Github: <https://www.github.com/linux-modder>
Facebook: <https://www.facebook.com/corey.sheldon>
Several Communities on Stack Exchange <https://www.stackexchange.com>

<http://www.facebook.com/1stclassmobileshine>

Tutoring in person or via any of the following platforms:
HackHands <https://www.hackhands.com>
Wizpert <https://www.wizperts.com>
FieldNation <https://www.fieldnation.com>
AirPair <https://www.airpair.com>
Truelancer <http://www.truelancer.com>

{PayPal,Google Wallet/Play store, Apple Pay}
---------------------------------------------------------------------------------------------------
pub  3072D/718BF597
<http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597> 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597
uid     Corey Sheldon (Fedora Key) <sheldon.corey@gmail.com>
---------------------------------------------------------------------------------------------------

**Comment by zetok** [comment] 2015-05-21 17:17
@vincenttschanz 
>Sorry I'm jumping on the bandwagon here, are you discussing about letting the user send a contact to another contact? 

Not quite. I was asking to close this issue, since current behaviour is an expected one. I.e. copying Tox ID of a contact is not and will not be possible, as far as toxcore is concerned.

That being said, please note that what you're asking about is not equivalent to copying contact's Tox ID, and somewhere in the future it should be possible to introduce, i.e. "send" contact to other contact, according to what @irungentoo said on IRC. This mechanism will not rely on manually sending Tox ID though..

**Comment by codedust** [comment] 2015-07-11 22:57
@irungentoo This can be closed as it's a duplicate of #1088 and sending friends to other friends is discussed in #1350.

**Comment by rysiekpl** [comment] 2015-12-03 13:09
Sorry to beat this (apparently) dead horse, but I do believe there is an argument to be made for the Tox clients to keep the full 76-digit ToxID in cache for users to be able to copy.

My use-case: I work in a large-ish organisation that requires secure, secret communication. Tox (specifically, qTox and uTox) is one of our tools of choice. We have people that we need to talk with all across the globe, and we need to be able to share contacts (in this case, full ToxIDs) between ourselves -- also when the person whose ToxID is being shared is offline at the moment.

There is no way to do this currently, and waiting for that person to come on-line, then asking them to provide their ToxID, and then sharing it with the person that needs to contact them, and then again waiting until both are on-line -- takes much too much time, and is completely unintuitive.

If qTox could cache the full ToxID, and make it available for the user with a disclaimer saying for example: "This ToxID might have become stale; in case of connection failure, please verify with your contact if that this is still their ToxID" -- that would be a huge boon for us, and would make it easier to convince people to use Tox that much easier.

P.S. Sorry for cross-posting this, not sure where it should go.

**Comment by zetok** [comment] 2015-12-29 18:25
@GrayHatter Is there a reason why this issue has been re-opened?

**Comment by ProMcTagonist** [comment] 2016-01-01 02:13
@rysiekpl It's going to be implemented with a protocol extension, @subliun is doing it for the android client.

**Comment by GrayHatter** [comment] 2016-02-12 21:51
Clients can cache the toxid they used if they wish, otherwise open an issue to query a friend for current nospam

**Closed by GrayHatter** 2016-02-12 21:51 UTC
Labels: Feature_Enhancement, idea, under_discussion
