### ISSUE TITLE
otr-like offline messages 

### ISSUE THREAD

**Issue by aaannndddyyy** [irungentoo/toxcore#1432] opened 2015-09-19 02:36 UTC
Currently, tox communication has otr-like features like forward secrecy and deniability (not really otr but still to some degree deniable)

Now offline messages are in the works too.

Ideally those should not be less secure than any other tox message.
But they are.

Therefore I propose adoption of the axolotl protocol for all of tox communication.

(Just like now, nacl/libsodium should be used and nothing be sent in the clear.)

**Comment by x368** [comment] 2015-09-19 08:41
+1

**Comment by Jeeppler** [comment] 2015-09-19 19:30
@aaannndddyyy If you are familar with the offline message development. Could you write a small article about them and contribute the article to: https://github.com/Tox/Tox-Docs

That would be awesome :-)

**Comment by ovalseven8** [comment] 2015-09-20 07:19
Why are offline messages less secure? @aaannndddyyy

**Comment by TheElf** [comment] 2015-09-20 07:40
@ovalseven8 I havent reviewed tox's implementation, but as a general rule, offline messages and perfect forward secrecy are mutually exclusive. 
This is because the key must be generated entirely by one party, and transmitted in such a way that it can be later read. 
IE the key cannot be ephemeral by definition, and if someone compromises a targets private key, they would have access to the message.

**Comment by ovalseven8** [comment] 2015-09-20 07:54
@TheElf: Well, as far as I know there is no Tox implementation for real offline messages yet. But I heard that something like the TextSecure protocol should be used for PFS: https://whispersystems.org/blog/asynchronous-security/#the-textsecure-protocol

**Comment by aaannndddyyy** [comment] 2015-09-20 13:50
@Jeeppler I do not follow the development too closely. And if it is still in flux it is hard to document.
Furthermore, https://github.com/DrakeFish/toxcore/tree/offline_storage is gone. I don't know where they are doing it now.
@ovalseven8 The information I got when I asked was that messages will be signed by the sender and encrypted to the recipient's pk. This is clearly not otr-style, and lacks some security features. 
Therefore, I recommend axolotl/textsecureprotocol.
Re "some thing like": Do not create your own protocol. If possible use an existing one.
And a third point: For consistency, if possible, all messages should use it then, not only offline messages. 
Why use two different protocols if one can cater for both situations? Using two means, double change to introduce bugs.
I know, that protocol assumes the existnece of a server for prekeys, but that is only needed for the asynchronous case. And it would improve the situation for normal messages too e.g. better deniability) and would not really slow things down, as the encryption/decryption is not affected, only key exchange/generation.

**Comment by GrayHatter** [comment] 2016-02-12 22:21
@aaannndddyyy why? be descriptive

**Comment by aaannndddyyy** [comment] 2016-02-12 22:35
Why what?
Why using two different enxryption schemes instead if one raises the risk of introducing bugs? Because of complexity.
 Or you are asking why signing a message makes it hard to deny that you authored the message?

**Comment by GrayHatter** [comment] 2016-02-12 22:42
> Therefore I propose adoption of the axolotl protocol for all of tox communication.

why should toxcore be completely rewritten to axolotl?

**Comment by aaannndddyyy** [comment] 2016-02-12 22:53
Only some routines, not all of toxcore.
You could still use nacl ir libsodium for actual encryption.

Why use it?:

It is a sound protocol.

It is one protocol for both direct and offline messages, instead of two protocols.

It has deniable authentication also for offline messages. With signing, offline messages woukd NOT be otr-like: no deniability, no perfect forward secrecy.

It enhances deniability over otr, which in turn is better than toxcore's current "otr-like" scheme.

**Comment by GrayHatter** [comment] 2016-02-12 22:56
how do offline messages work in axolotl?

How does it maintain deniability and OTR and also using libsodium?

**Comment by aaannndddyyy** [comment] 2016-02-12 23:05
Axolotl is just about the key exchange. It does not do offline messages, but it allows you to have pfs when encrypting offline messages.
The basic idea is simple. Yiu dont use longtime keys for encryption. Just like otr or current toxcore do in normal "life" messages. The only problem to tackle would be tge distrivution of the prekeys. Axolotl was developed for secure im which are server-based. But contacts can share a certain amount of them when they see each other online and tben use those for offline, so the server is not indispensible.
Axolotl does not necesarily do the actual encryption, this can be done with nacl.

**Comment by GrayHatter** [comment] 2016-02-12 23:11
I don't understand anything you just wrote...

**Comment by aaannndddyyy** [comment] 2016-02-12 23:19
It's basically just a scheme of several Diffie-Hellman's

**Comment by Jeeppler** [comment] 2016-02-13 22:50
@aaannndddyyy otr or axolotl (protocol) does not address the key issue. The key issue is offline messages in a distributed node system where availability of clients is not guaranteed.

**Comment by GrayHatter** [comment] 2016-02-14 00:39
closing; for insufficant information for this to be a proposal, or a complete bug report / feature request

**Closed by GrayHatter** 2016-02-14 00:39 UTC

**Comment by aaannndddyyy** [comment] 2016-02-14 03:51
@Jeppler This issue is not about offline messages per se, i.e. fir how they are stored in a p2p system without disclosing who communicates with whom and without allowing to flood the dht with offline messages. This is posdible to do, but not the focus of this issue, there is another issue for that. This one is about security and privacy. The way offline messages were planned was much less secure than direct messages are now.
This is not desireable.
That's what this issue is about.
Even current messages are not as secure as otr is. But offline messages or groupmessages are even less secure.
And as a solution to this problem is not only desireabke, but already exists, I suggested using it. Axolotl with nacl and a p2p messenger would make a pretty neat system

**Comment by GrayHatter** [comment] 2016-02-14 04:28
> Even current messages are not as secure as otr is. But offline messages or groupmessages are even less secure.

why do you say that?

**Comment by cmotc** [comment] 2016-02-14 06:26
I don't know much of anything, I just read alot, and I've not committed
a line of code to toxcore yet so maybe it's not my place, but I was
reading about the proposed one-time reply mechanism in
MixMinion(mixminion.net/minion-design.pdf) and going through the old
issues and pull requests(I'm really, really interested in Tox, and I was
reading the various issues in which people raised multiple device
proposals and offline messaging proposals and the relationship between
those two needs) and it gave me an idea about how a Peer-to-Peer
Axolotl-Like system could resist disclosing metadata in certain contexts
in something like Tox, however it would probably also inflate the amount
of data a client would need to store considerably and increase how long
it takes for clients to become useful at runtime as well. It might not
even really need to change the core, my plan was to try it using ratox
and some scripts and see what's up, I just haven't finished updating
it(ratox) to the new API yet.

I have very little formal training, like I said, so I'll try to explain
my idea(which I feel like is entirely too simple to have been overlooked
before, but I keep going back through all these issues expecting to find
it and I don't, or at least I don't think I do, but I don't fully
understand everything yet and I doubt I've read every issue and pull
request, much less the actual code) as systematically as I can.

First, a user downloads a client and it generates an ID, hitherto
referred to as the long-term ID. Joins the network.

Second, the user adds his first friend. They are both connected to the
network.

Third, both users immediately generate a new, additional ID called the
temporary ID. These are exchanged over the established encrypted channel
and the users are prompted to accept the temporary ID's for sending
offline messages to eachother because they are both still connected to
the network since they just added each other.

This is the part where I'm already pretty sure I'm still missing something.

Fourth, maybe they talk a little while before one of them disconnects
from the network.

Fifth, an online client wants to send a message to an offline friend
without disclosing his or her own long-term ID. He or she clicks on the
same nickname his or her friend uses when he or she is online and types
a message. Instead of sending it with the long-term ID, he or she sends
it with the temporary ID, to the other user's temporary ID.

Sixth, the offline message is sent to some kind of relay, with only the
temporary ID's of both the online and offline parties to the offline
message. I think it could be pretty much anywhere in this form? Bit of a
blank here, obviously.

Seventh, the offline client comes online and re-joins the network with
his long-term ID for the duration of the session and joins with the
existing temporary ID's to retrieve stored messages from hypothetical
relays for as little time as possible.

Eighth, if two users who are already friends bring their clients online
at the same time they discard their existing offline ID's and generate
new ones. This step is repeated every time 2 clients who exchange
offline messages meet.

Anyway, just trying to help. Maybe when you create a group with offline
messengers it does some kind of blind carbon copy thing? I can think of
a few ways in which it might be weak but I don't know enough to know for
sure what 2 ID's connected from the same computer at the same time
reveals in any complete sense. I feel long-winded and audacious. I
really hope I'm not embarassing myself but I can't help by not
participating.

aaannndddyyy:

**Comment by GrayHatter** [comment] 2016-02-14 08:33
@cmotc that's not a novel idea, and would be somewhat trivial to implement, but step 6 is where we are right now.

Encrypting the messages such that they don't disclose who wrote them, or who's receiving them is easy enough. The hard part is getting them from sender, across an untrusted network to the receiver is the hard part.

**Comment by cmotc** [comment] 2016-02-14 09:14
If you don't mind just nailing this down for me, do you mean that the issue is relaying the message from the sender to the reciever without tending to increase centralization, and not so much the potential for the information being transported to reveal something about itself to an intermediary in some way?

**Comment by GrayHatter** [comment] 2016-02-14 09:15
And in a way that can't be, or is very difficult to abuse.

**Comment by SkyzohKey** [comment] 2016-02-14 12:58
Why not encrypting the message with the receiver public key and broadcasting the offline message to all the network ? Only the man that own the public key would be able to decrypt using it's private key, since their is no meta data about the public key, you doesn't know who is the send/receiver.

Note that i can be wrong. ;)

**Comment by aaannndddyyy** [comment] 2016-02-14 14:29
Why not?
Because it would increase the traffic load too much. It does not scale.
And it is less secure.
And furthermore could even leak metadata.

**Comment by TheNain38** [comment] 2016-02-14 14:33
And how do you know from who the message came from? And to who the offline message should be send?

**Comment by aaannndddyyy** [comment] 2016-02-14 14:57
That's not trivial, but also not overly complicated. But not part of this issue.

**Comment by TheNain38** [comment] 2016-02-14 16:19
@aaannndddyyy I was talking to @SkyzohKey when writing this

**Comment by SkyzohKey** [comment] 2016-02-14 22:38
@TheNain38 The guy that would be able to decrypt the message is the receiver. Simple as this.

**Comment by aaannndddyyy** [comment] 2016-02-14 22:52
Does not scale

**Comment by LuccoJ** [comment] 2016-02-14 23:32
@aaannndddyyy it might not scale, but broadcasting the message to every peer, knowing that only the intended recipient will be able to decrypt it, is how Bitmessage works, and that's currently one of the few non-realtime distributed messaging systems that exist.

**Comment by fuloating** [comment] 2016-02-15 15:20
Not sure if i'm contributing at all but just mentioning here what someone mentioned on #tox couple days ago aswell: webrtc-explorer https://github.com/diasdavid/webrtc-explorer uses chord, and probably has that time-shared storage implemented in it(?) Could it have something to look at maybe or not suitable for temp storage on IM's?
https://pdos.csail.mit.edu/papers/chord:sigcomm01/chord_sigcomm.pdf

> Time-Shared Storage for nodes with intermittent connectivity. If a person wishes some data to be always available, but their machine is only occasionally available, they can offer to store others’ data while they are up, in return for having their data stored elsewhere when they are down.
