### ISSUE TITLE
indiegogo fundraising Campain.

### ISSUE THREAD

**Issue by irungentoo** [irungentoo/toxcore#1397] opened 2015-08-04 19:36 UTC
https://www.indiegogo.com/projects/toxcore-development

Just confirming here that this is legit and by me.

**Comment by im-grey** [comment] 2015-08-04 20:05
I want to give money, I have given money before, but how can we be sure it will not be stolen this time?

**Comment by irungentoo** [comment] 2015-08-04 20:11
This money is going directly to me so it won't be stolen.

**Comment by hsimons** [comment] 2015-08-04 20:56
Last time the money also went to a person on the Tox Foundation that you said was solid and would have no problems, @stqism.

https://lwn.net/Articles/651003/

How can we be sure the money donated will really be used to what you say and not for personal matters like college tuition, private servers, etc. (like it happened last time).

I think developers deserve to be paid for their hard work, but in the case of Tox it's very hard to trust things will happen as the developers say, given the shady past it had.

How can you **convince** the community to donate? I want to, but I'm not sure my hard-earned money will be put to good use, since it wasn't last time.

But I really believe Tox has to be further documented, so I'll give a +1 on that. I had trouble going through the code without documentation: https://github.com/irungentoo/toxcore/issues/1398

https://lwn.net/Articles/651003/

**Comment by irungentoo** [comment] 2015-08-04 21:01
@hsimons it clearly says on the indiegogo page that this is to pay myself and that the money goes straight to me.

**Comment by czarkoff** [comment] 2015-08-04 21:01
@hsimons, @im-grey: Please, either donate or not, but don't turn it into another round of flame war.

**Comment by hsimons** [comment] 2015-08-04 21:04
@irungentoo 
But the other time you asked for donations, your website said money would go to development too, but in the end it was used to pay Qureshi's college tuition and other personal debts. Words don't mean much now that the trust has been lost. Is there no way the community can be sure the money will be put to good use?

@czarkoff 
I don't see any flam war here. I actually want to donate if it's for a good cause, but given the past, I'm not sure, that's all. It would be good if irungentoo could convince the community that he is solid and the money will be used for a good cause. But I think because of the shady actions of the past, simple words won't be enough for us.

**Comment by irungentoo** [comment] 2015-08-04 21:22
@hsimons This is me fundraising money for myself, not on behalf of a foundation. It's clearly written on the page that this money will go to me. Why would I lie about money going straight to me? It makes no sense.

It sounds like you are just here to stir shit up.

**Comment by hsimons** [comment] 2015-08-04 21:24
@irungentoo 
Okay, I understand the money will go to you, that's obvious.
But how will you use this money to further the development of Tox? In which way this money will be used? What can the community expect out of it and how can we be sure of it?
I'm sorry if you think I'm here to "stir shit up", but after what happened last time (donation money stolen and used to pay private debts) you really can't blame our skepticism.

**Comment by d9h02f** [comment] 2015-08-04 21:26
The sheer dedication of whoever's behind all these accounts is certainly admirable.

**Comment by czarkoff** [comment] 2015-08-04 21:51
@hsimons You can never be sure. Maybe some script kiddie will break into banking account, take all the money, spend it on booze, hookers and cocaine and die of overdose before cops arrive.

Really, either you trust @irungentoo and give him money, or you don't and stay away. It is just that simple.

P.S.: IMO it is time to close this issue.

**Comment by hsimons** [comment] 2015-08-04 21:56
@czarkoff 
You blowing everything out of proportion doesn't help the cause.
Of course we can't be 100% sure, but being completely in the black isn't good.
Are there any measures that @irungentoo will enforce to make the community trust this a bit more? Because right now this is the exact same situation we were in when we donated money that was later used by @stqism to pay for his debts, college tuition and other unrelated stuff.
The question is simple. How will the money be used by @irungentoo to further development of Tox? How does he expect us to trust it, by posting the receipts online or something like that? What are the exact roadmaps? I want to give a big +1 for documentation, that's really needed.
Another +1 would go to make Tox actually fully decentralized, because right now it isn't.
But I don't think anyone will donate until we get more information and more security that the money will be used for a good cause.

**Comment by czarkoff** [comment] 2015-08-04 22:12
@hsimons You are asking @irungentoo to change something in your head, not in real world. This quest is deemed to fail.

Again, it is a simple matter of trust. Even if @irungentoo provides some evidence that these money won't be wasted, it still would never guarantee that in some point in future he or someone else won't cripple enough to make these money effectively wasted, even if they would be spent most wisely until then.

Furthermore, there is absolutely no way to enforce proper spending of these money. This way or another they still could be stolen and used to pay one's depts, college tuition and other unrelated stuff.

So just stop flaming and get over it.

**Comment by irungentoo** [comment] 2015-08-04 22:12
@hsimons The money will be used to pay me to work on Toxcore. You will easily be able to see how much I work by looking at my github profile and my commits.

**Comment by hsimons** [comment] 2015-08-04 22:21
@irungentoo 
OK, the money will be used by you. But on what exactly? That's the question that stays unanswered. Will you use the $5000 for a security audit? To pay for http://tox.im servers? What will it be used for? We just don't want to see the @stqism situation repeated again, where he used the money for his college tuition and personal debts instead of helping Tox development with the money. At least he's been kicked from the project now, right? But we have a reason to be skeptic.

**Comment by irungentoo** [comment] 2015-08-04 22:26
@hsimons As is clearly written on the indiegogo page, this money will go towards paying myself for at least 1 month of full time work on toxcore.

**Comment by suhr** [comment] 2015-08-04 22:37
I'm not enjoying such a campaign too early. Tox should first restore some trust and merge some important things (new toxav, groupchats).
:-1:

**Comment by irungentoo** [comment] 2015-08-04 22:42
@suhr if this campaign doesn't succeed my time to work on Tox will most likely drop even more which means it will take even more time to get new groupchats, etc...

**Comment by irungentoo** [comment] 2015-08-04 22:42
unless someone else takes over of course.

**Comment by Astonex** [comment] 2015-08-04 23:52
>unless someone else takes over of course.

Maybe if you had written any sort of documentation or protocol specification, that would be an actual possibility but you've purposely not done so you can keep control of the development yourself. And now you're asking for money to do these things you should have done before even starting on the code

**Comment by hsimons** [comment] 2015-08-04 23:58
@irungentoo could you please develop a bit more on why not getting $5000 from the community would make you slow down contributions to Tox? I don't see the connection.
And @Astonex does have a point, there have been lots and lots of requests to give proper documentation on the toxcore so others could work on it, fork their own version, etc.
It's been over 1 year since mahkoh stop working on his Rust rewrite of Tox because there weren't proper docs. https://github.com/mahkoh/Xot/blob/master/README.md
And even before that others were asking for a formal specification of the protocol.
It's a basic thing to do on any project, especially when it's as sensitive as Tox is.
But you request $5000 to do it? I don't follow. I simply don't follow.

**Comment by irungentoo** [comment] 2015-08-05 00:51
@astonex I am asking for money so that I have time to actually do those things.

@hsimons 
>could you please develop a bit more on why not getting $5000 from the community would make you slow down contributions to Tox? I don't see the connection.

If I can't earn money from Tox development I need to earn it by doing something else which means a lot less time for Tox development.

**Comment by hsimons** [comment] 2015-08-05 00:53
So this indiego campaign is kind of a salary you want? It will be spent with your personal affairs, not with anything directly connected to Tox? The community will be kind of hiring you, if I understand correctly, and you use the money as you wish.

I'm not sure how I feel about this...

**Comment by im-grey** [comment] 2015-08-05 01:44
@irungentoo Alright, thanks.

**Comment by ProMcTagonist** [comment] 2015-08-05 03:48
Presumably he'll use it on food so he can sit in his basement/office/cave and work on Tox 100% of the time, which sounds really nice. That sort of thing doesn't mesh really well with big-burst one-time fundraisers, though. Have you considered a Patreon?

Another funding solution I've seen mentioned in connection with avoiding more quereshi problems is https://snowdrift.coop/.

**Comment by anonymous-4chan-user** [comment] 2015-08-05 06:57
Disclaimer, made an account to comment.

>@astonex I am asking for money so that I have time to actually do those things.
>@irungentoo could you please develop a bit more on why not getting $5000 from the community would make you slow down contributions to Tox?
>@suhr if this campaign doesn't succeed my time to work on Tox will most likely drop even more

I'm sorry, but this feels like you're trying to threaten us in to giving you money otherwise you'll stop working on toxcore.

:-1:

>Presumably he'll use it on food so he can sit in his basement/office/cave and work on Tox 100% of the time

As I've heard on IRC he lives at home and is bad at school and doesn't actually have any real IRL expenses.

>Maybe if you had written any sort of documentation or protocol specification, that would be an actual possibility but you've purposely not done so, so you can keep control of the development yourself

I agree with this, I remember him asking for money to do protocol specs and other times offering to do so, but lets it die so he doesn't have to. I'm now 100% sure it's so no one else can replace him.

>I'm not enjoying such a campaign too early. Tox should first restore some trust and merge some important things (new toxav, group chats).

If this was in a year or two when all the drama has settled and he came with an organized plan with data on expenses, etc I'd support it, but not this cash grab.

@irungentoo: You might not understand this, but people write free software for the good of its users, not in some sort of pity cash grab to bank out on it. Here's an essay from Richard Stallman on why software should be free, he talks about a bit about why people actually make free software. http://www.gnu.org/philosophy/shouldbefree.en.html (Tip: there isn't an economic reason)

**Comment by ameenross** [comment] 2015-08-05 08:01
I really have no problems with developer time being paid for, nor does RMS:

>  The question “How can we pay programmers?” becomes an easier question when we realize that it's not a matter of paying them a fortune. A mere living is easier to raise.

Furthermore, I find it absolutely uncalled for to require @irungentoo to cough up a list of all his personal expenses. And that coming from supposed privacy advocated is simply unfathomable.

Please don't justify these 'concerns' by pointing out problems with documentation or other issues with the project. Those are problems of themselves, which, by the way, you can address yourself by contributing. Seriously, the issues mentioned by @hsimons are issues I already knew and I never really looked at Tox code, and I'm sure he didn't either. But for those who really did, why not contribute documentation yourself? Is it because you don't have the (unpaid) time for it? In that case it's even hypocritical to call out @irungentoo for starting a funding campaign. If it is because you don't care, then please get off this project's lawn. Your flamewars don't help anyone in any way.

**Comment by anonymous-4chan-user** [comment] 2015-08-05 08:33
>But for those who really did, why not contribute documentation yourself? Is it because you don't have the (unpaid) time for it?

Because the code itself is so horribly undocumented that no one really understands it at all.

@Astonex and at least 2 others Have offered on multiple occasions to write it if @irungentoo explains it to him, and @irungentoo promises to do so. Everyone is okay with @irungentoo saying that code won't be worked on for like a week if he goes through and does that. He then ignores everyone when the hype has died down a week later and refuses to actually do it.

>Those are problems of themselves, which, by the way, you can address yourself by contributing (it's open source remember, not some kind of proprietary project)

Is it really valid if it's been written and designed in a way to specifically prevent most outside contributions without the graces and week of explanations from @irungentoo?

I remember when the new groupchats were being first made, the GSoC student had to ask @irungentoo about every little thing because it was poorly named and lacked any documentation as to what does what. The'd get really frustrated because he'd then turn around and respond with a tiny or unhelpful response and refuse to reply to attempts at clarification.

>Seriously, the issues mentioned by @hsimons are issues I already knew and I never really looked at Tox code, and I'm sure he didn't either.

I'm using this account anonymously, but I actually have contributions to toxcore itself on my main. I've read a lot of the codebase a ton of times to understand and attempt to figure part of it out, it's more enjoyable to stick your head in the garbage disposal.

>But for those who really did, why not contribute documentation yourself? 

After over 2 years I've come to the realization that toxcore was written with the goal in mind to prevent this from happening if it didn't come from @irungentoo without at least months of work.

**Comment by ameenross** [comment] 2015-08-05 08:46
So is this really a political forum or is this the issue queue for a code repository? Post your concerns on your personal blog, on 4chan or somewhere else. I'm following this project to see its progress, not to see flamewars and discussions on whether or not @irungentoo is holding Toxcore hostage (that may or may not be the case, I really don't care enough at the moment as Tox is far from done).

**Comment by ameenross** [comment] 2015-08-05 08:51
> I'm using this account anonymously, but I actually have contributions to toxcore itself on my main.

Actually, especially the fact that you're posting anonymously despite having an account is something that puts me off.

**Comment by LapFox** [comment] 2015-08-05 09:11
$5000 for one month of development? I don't think a one-off payment is a mechanism I could get behind for this.

A monthly Patreon I'd happily contribute to, however as it stands, I won't be contributing.

**Comment by LittleVulpix** [comment] 2015-08-05 10:30
@irungentoo , I agree with @LapFox , Patreon is perfect for this kinda stuff. I can get behind that as well.

**Comment by AlexDaniel** [comment] 2015-08-05 12:01
I see no problem with this, even if it is there to provide a 1-month salary.

This is not some uncommon practice. Like, some of the Perl6 developers are actually getting paid. For example, see this: http://news.perlfoundation.org/2015/04/grant-proposal-perl-6-release.html. It is a really good way to boost development. That's basically the only way to make some people work on the missing parts, who may otherwise be busy writing proprietary software instead.

And if you're still struggling to accept this fact, make sure to check out the numbers on the provided link. If it feels weird, then check out what this person has done during that time. If not some grants like this, then it would be much harder to get perl6 done till the end of this year.

I really think that tox development needs something like this. It is taking way too much time to make it kinda-“ready”.

If you don't want to support it – that's fine, but please stop trying to convince other people not to help.

**Comment by hsimons** [comment] 2015-08-05 13:17
@ameenross 
> why not contribute documentation yourself?

The problem about users trying to contribute to documentation is that the toxcore code is messy, doesn't have a consistent coding style, is all over the place, lack comments, etc. If you tried to read it, you would know. Ask @Astonex or @mahkoh They tried working with toxcore before, but failed because of lack of readability. If this is something irungentoo does on purpose like Astonex claims, I'm not sure, Would need more proof on that. But anyway, the issue exists.

> Your flamewars don't help

I'm sorry if you see a flamewar here, all I see is community members raising valid concerns about Tox, because of what happened last time when money was involved. https://lwn.net/Articles/651003/

**Comment by ameenross** [comment] 2015-08-05 13:36
> I'm sorry if you see a flamewar here, all I see is community members raising valid concerns about Tox, because of what happened last time when money was involved.

Yeah see... I know what happened, you don't have to keep posting that lwn link every time to try to force your point across. I still fail to see what that has to do with a Github issue queue for a *code repository*. This is intended for technical discussions and that's the only reason I'm watching these issues. You are therefore polluting my GH notification center.

Again, post your concerns on 4chan, your personal blog, facebook, whatever. I DO NOT CARE.

**Comment by hsimons** [comment] 2015-08-05 13:56
> I still fail to see what that has to do with a Github issue queue for a code repository

Ask irungentoo then, he was the person who opened this issue.
He opened an issue about his "indiegogo fundraising campain [sic]" and now the community is clearing their doubts about the campaign. That's all. It looks like you are trying to dismiss all concerns people have by all this off-topic posts. Let's keep this on-topic: questions about the donations. That's it.

> polluting my GH notification center

Again, irungentoo created this issue.
Don't want to see it? Unsubscribe.
You are the one polluting what was a good debate between developer-community by posting all this unrelated stuff.

> I DO NOT CARE

Then unsubscribe from the issue and stop whining here.

**Comment by mahkoh** [comment] 2015-08-05 14:17
>https://lwn.net/Articles/651003/

What a time to be alive when lwn writes articles about /g/-tier shitposting.

>>Maybe if you had written any sort of documentation or protocol specification

>@astonex I am asking for money so that I have time to actually do those things.

I reverse-engineered large parts of the protocol within two days back in April 2014 by going through the toxcore code. Why does someone who already knows the code and the protocol require $5000 to write the protocol down? Unless [you](http://catb.org/esr/writings/unix-koans/prodigy.html) have already forgotten half of it.

If the fundraiser were to fail and if you were to stop working on toxcore, would you not be sad that the project died with you and that all the effort was for naught?

**Comment by ameenross** [comment] 2015-08-05 14:25
> Ask irungentoo then, he was the person who opened this issue.

The only reason he posted it was to clearly indicate to the community that the campaign is really his an no-one else's. Developers who might want to support him know him only by his GH handle so that seems legit to me. I've already proven you to be a troll.

There may or may not be valid concerns about the Tox foundation or even the conduct of individual developers, but I see no reason that belongs on the issue queue for a *code repository*. You yourself complained over at the other issue for my lack of engaging in a technical discussion. Go read it again.

**Comment by hsimons** [comment] 2015-08-05 14:31
@ameenross 
Man, this is getting old. Don't want to take part of this debate? Unsubscribe from the issue.
But you polluting the discussion with inane comments and ad hominem is no good!
Really, we are discussing technical issues here: in which way will donations further tox development.
@mahkoh and @Astonex brought up really good points about documentation and how they don't see the donations fitting the picture. You are the one derailing the thread and I politely ask you to stop.

Another thing came to my mind.
@stqism was fired from the Tox Foundation because he used donation money to pay his personal debts.
But isn't @irungentoo asking for donation money to pay his personal debts right now with this indiego campaign?
Maybe it's because in @stqism case he didn't say beforehand that he would do it, but pretended it would go to tox development? If this is it, it would be really important for irungentoo to give exact details on how he will spend the money. Tox development? Security audit? Pay for food? College tuition? Whatever it is, tell people who are donating, just so there's no misunderstanding in the future like happened in stqism case.

**Comment by ameenross** [comment] 2015-08-05 14:51
> If this is it, it would be really important for irungentoo to give exact details on how he will spend the money.

He already answered that above. The fact that you're not happy with his answer does not mean you need to keep repeating the same question over and over again.

> @mahkoh and @Astonex brought up really good points about documentation and how they don't see the donations fitting the picture.

I've seen that tactic before; hiding behind reputable community members. You're going much further than them, however. You have no standing to speak of in the community, yet you claim to speak for it. I have seen that before as well.

**Comment by hsimons** [comment] 2015-08-05 14:55
> He already answered that above

Could you provide then, what irungentoo will use the donation money for, exactly? I just think this has to be absolute clear right now, so there's no misunderstandings like last time, that's all.

> hiding behind reputable community members

Again, can you please focus on the actual issues and discuss them, instead of screaming that everything is a conspiracy, that my account is fake (even though I have it since 2010), that everyone not donating is a troll, etc.? This is really uncalled for and is only derailing the thread. Let's keep a real discussion or keep quiet. Thank you.

**Comment by AlexDaniel** [comment] 2015-08-05 15:03
@hsimons as I've already mentioned in https://github.com/irungentoo/toxcore/issues/1397#issuecomment-127972775, whether he spends this money for the project needs or just for food, a lot of us just don't care. Deal with it.

**Comment by hsimons** [comment] 2015-08-05 15:08
@AlexDaniel 
> whether he spends this money for the project needs or just for food, a lot of us just don't care

But a lot of us care.
A few weeks ago @stqism asked for donations and used it to pay his college tuition, which created a big buzz from the community and other Tox Foundation members, because he spent the money on personal stuff and not "for the project needs". All I'm asking is for a clear explanation from @irungentoo so that there is no misunderstanding. We don't want to see all that situation again.
Don't you agree it's better to settle matters now then after the money is donated? Just so there is no misunderstanding.

And how @mahkoh pointed out, and @Astonex before, it's a bit weird if all the money will be spent on personal stuff and not really a security audit or something like that. Raises some other questions... Let's wait for @irungentoo and the official response on this situation. Hoping for the best.

**Comment by SunShiranui** [comment] 2015-08-05 18:58
To me it seems pretty clear what the money is for. It's stated explicitly on the indiegogo campaign.

The money will be used to pay irungentoo to work full time on toxcore, as opposed to him working out of good will in his spare time.

I don't see anything wrong with a developer asking for donations for his work. He is free to spend the money as he pleases, like every worker in civilized society.

**Comment by nurupo** [comment] 2015-08-06 08:24
@hsimons
Not really sure what is the issue you are having with this indiegogo.

It's a fundraising made solely by irungentoo for himself. He is the one who created it and the one receiving money from it. No one else is involved in it. It's just as if you yourself created a fundraising for you to work on Linux kernel, assuming you have some expertise in that. It's just like a individual developer donation thing. Thus no once controls how he spends money but him alone and no one is going to control or nag him about what he does or doesn't do as the result of the fundraising, since it's his personal thing -- it's not Project Tox fundraising, it's just irungentoo fundraising.

As far as what he is collecting the money for, the indiegogo page should answer that. If not, then irungentoo made a poor job composing it, maybe you could suggest him how it could be improved. My understanding of it is that he wants to work on Tox related things full time, and for that to happen he wants to be financially independent during that time, so that he doesn't have to work full time at some place of employment at the same time and could dedicate all his time to Tox. Time is a very precious resource in FOSS world, so you shouldn't underestimate it and you also shouldn't assume that people working on FOSS are obligated to do anything at all -- they work on those project purely voluntarily. Here is a quote that I really like and which explains this in better words:

>It is important to understand that most people contribute to open-source in their free time, out of joy. The time we choose to work on open source is time we could otherwise spend hanging out with friends and family, or programming for money, or reading books, or watching television, or just sleeping. We steal time from the rest of our lives because we love to code and we want to make the world a little bit better by creating great software. ([source](http://softwareswirl.blogspot.com/2014/03/my-secret-tip-for-gsoc-success.html))

I see that documentation was mentioned in this issue. So, is documentation something we want irungentoo to write? Of course yes, we want Tox protocol to be well documented to the point that you could re-implement toxcore (what mahkoh was trying to do in Rust) and audit the security of the protocol based on the documentation/specification alone (not to confuse with auditing toxcore, which is an implementation of the protocol). Is it something he is obligated to do? No, he is not obligated to do anything, not even work on toxcore. It's his free time, there is no contract or boss in here that would force him into working. @anonymous-4chan-user that's also a reply to you.

**Comment by retuxx** [comment] 2015-08-06 08:41
+1

**Comment by codedust** [comment] 2015-08-06 10:36
+1 to @nurupo 
Imho it's totally legitimate to be paid by the community. Yes, there is some loss of trust in some developers, but that's why @irungentoo collects the money by himself and not in the name of the Tox Foundation. Everyone can decide whether he/she trusts @irungentoo or not.

However, there is one thing I don't really like about the campaign:

```
$500USD
Name a variable in toxcore.

Make your mark in toxcore. Your variable name must be 20 characters
or less and must contain only letters from the 26 ones in the english
alphabet and the _ character.

You also get all the previous perks.
```

As we have seen, keeping the source readable is very important. Hopefully, people who are willing to contribute $500 or more will not try to abuse this.

**Comment by ovalseven8** [comment] 2015-08-06 13:08
Also if the Indiegogo campaign is not an official project of Tox, you should make a blog post and a little bit publicity. 

How should potential contributors know that there is a campaign? @irungentoo

**Comment by czarkoff** [comment] 2015-08-06 13:11
@nurupo, @codedust, @retuxx, @SunShiranui, @AlexDaniel and others: please, stop feeding the troll. Let this "issue" die.

**Comment by friend1** [comment] 2015-08-09 16:08
I am a friend of Harry (hsimons)
We know each other since we were kids and he asked me to post here so everybody knows what happened to him. I'm not really a computer person, but signing-up to this site was easy enough.

hsimons was banned from this repository without any reason while he was discussing the issues.
Here is what he told me.

>Most issues I had with the indiegogo campaign and partially-centralized nature of Tox won't properly addressed and instead I was banned from the repository by irungentoo.
Really, what were they thinking with this donation plan right after money was stole? And how is it different from when Sean stole it? stqism was fired from the Tox Foundation because he used donation money to pay his personal debts. But isn't irungentoo asking for donation money to pay his personal debts right now with this indiegogo campaign? Double-standard?
And I do believe my concerns about Tox being partially-centralized but not being clear about it are also valid and unanswered properly. I even proposed a simple solution and asked all client developers to come and discuss it. https://github.com/irungentoo/toxcore/issues/1398
My proposal, as soon as the user opens a Tox client, he is prompted with the following option:
---- Choose your communication mode ----
1) Better Performance | Less Privacy
2) Better Privacy | Less Performance

>I tried continuing conversation on the issue #1397 with the following:
@nurupo
Well said, maybe irungentoo should have posted a detailed reply like yours from the very start to avoid misunderstandings. So I understand @irungentoo wants money so he doesn't have to work and can focus on Tox? Correct?
@codedust
Agree on that, readability is really important, just like documentation, and that's a weird perk. Naming a variable? The donator will call it his own name or something? Doesn't sound like that good of an idea.
@czarkoff
Unsubscribe from the issue if you have nothing to contribute and think everyone that doesn't automatically bow before Tox and thinks the Foundation is perfect is a troll. We are having a real discussion here and your blatant off-topic post is only polluting it. @codedust raised a true concern about naming variables, how about you discuss that instead of calling him a troll feeder or whatever? Or just go away if you have no interest in contributing to this debate.

>Only to see that I was banned.
A software that advertises as caring about users, the community, privacy, etc. enforces censorship when someone raises issues with their software? What the hell?

I don't really understand much of all this talk, I'm a highschool teacher, not a computer guy, but Harry is a great person and I think you should unban him.
Censorship is never good as we learn from history books.

Thanks.

**Comment by blobgo** [comment] 2015-08-21 11:15
What a discussion, but let's switch to another nicer topic and get back to the fundraising.
At the indiegogo campaign there is one perk:
> Become the Boss

>I will work full time for 1 week (40 hours) on the Toxcore feature of your choice (Can be anything at all). Also includes the Super Donator perk.

And actually one person has chosen it, WOW. So @irungentoo would it be possible you could tell us what feature the person choose?
I mean we would see it anyway when it's implemented but I'm quite curious what it might be...

(BTW maybe this perk would be something for @hsimons so that he knows that he donates money for a special feature, which would answer his question for what the money is spend)

**Comment by GrayHatter** [comment] 2015-08-21 21:42
@blobgo hsimons is a troll with the goal of stirring up shit and trying to create FUD, he's been banned...

In other igg news, irungentoo is just under 50% funded with slightly less than 1/2 the month remaining, now would be an ideal time to donate! Help get toxcore the development time needed to be as awesome as we all know it will be.

**Comment by codedust** [comment] 2015-08-22 11:09
@blobgo The chosen feature for the `Become the Boss` perk (chosen by @LittleVulpix) was improving file transfers which could be more reliable than they are right now, especially on slow connections.

**Comment by Jeeppler** [comment] 2015-08-22 18:27
nice :-)

**Comment by urras** [comment] 2015-08-25 15:40
@friend1
>I am a friend of Harry (hsimons)
>We know each other since we were kids and he asked me to post here so everybody knows what happened to him. I'm not really a computer person, but signing-up to this site was easy enough.

How desperate can you be neeh?

**Comment by Jeeppler** [comment] 2015-08-27 13:25
@friend1 first of all @irungentoo asks directly for money to pay himself for one month and 5.000 $ is not that much for an experienced developer like him. If he pays his debts with this money in the one month I don't care, as long as he does the development in this month.
To be clear, there is always the risk that something happens, but investing e. g. 25 $ in an Indigogoo campaign does not make most of the people homeless.

and either you @friend1 or @hsimons are trustworthy enough. Who knows, maybe your are from an agency of some country. Nobody knows that, but @irungentoo does a lot of work, everybody can see what he does for this project. On the other hand @hsimons have not contributed to this project at all.

**Comment by friend2** [comment] 2015-08-27 16:09
First, it's very convenient for you all to ban @hsimons and me and then talking bad about us.
hsimons told me to ask "but @stqism was kicked from the project because he used donation money to pay his personal affairs. Now @irungentoo is asking for donation money so he can... pay his personal affairs! Isn't this double-standard? Also, everything is too evasive and shady, irungentoo doesn't explains things completely".

NOTE: this isn't an exact quote from Harry, we talked on phone and this is more or less what he said.

Thank you.

**Comment by LittleVulpix** [comment] 2015-08-27 16:20
I can't believe anyone would go as far as to talk to their friends about some random github project on the phone. Most people would just give up. I don't believe that you're not hsimons even for a second :p Either that or you and hsimons are best friends for life and you are doing him a super big favour :dancer: 
Irungentoo is not shady, he said exactly what the money goes for, and you are paying for toxcore development. Well not you, but contributors.

**Comment by Jeeppler** [comment] 2015-08-27 17:24
For both @friend2, @friend1 and @hsimons everybody is polite, the only guy who was not is @hsimons. 

@LittleVulpix for all other arguments look at @LittleVulpix's post above.

**Comment by ProMcTagonist** [comment] 2015-08-29 18:41
> @stqism was kicked from the project because he used donation money to pay his personal affairs. Now @irungentoo is asking for donation money so he can... pay his personal affairs! 

No.

> Isn't this double-standard?

No.

>secretly stealing money from other people's donations and asking for personal donations is the same thing

you're not worth talking to

**Comment by GrayHatter** [comment] 2015-08-29 18:52
Don't feed the troll

**Comment by optimumtact** [comment] 2015-09-04 00:59
congratulations on the successful funding

**Comment by GrayHatter** [comment] 2015-09-04 02:03
@irungentoo congratulations, it seems as this bug can't be reproduced
because the campaign funded... so I think it's safe to mark this as fixed
and close it?

**Comment by fcore117** [comment] 2015-09-04 03:39
success and congratulations, this is news of the day.

**Comment by Jeeppler** [comment] 2015-09-04 06:48
:+1:

**Comment by LittleVulpix** [comment] 2015-09-04 07:25
lol @GrayHatter , nice meme :+1 but yeah! GJ on successful funding! Hopefully this will propel tox forward by a few light years.

**Comment by urras** [comment] 2015-09-04 15:40
Wow, congratulations guys!

**Comment by GrayHatter** [comment] 2015-10-01 19:21
@irungentoo close completed

**Closed** 2015-10-20 16:40 UTC
