### ISSUE TITLE
Change an Already Sent Message

### ISSUE THREAD

**Issue by srkunze** [irungentoo/toxcore#1261] opened 2015-02-16 18:12 UTC
Skype features the ability to change an already sent message. I found this to be useful. Can this be done?

**Comment by Impyy** [comment] 2015-02-16 18:14
Duplicate of https://github.com/irungentoo/toxcore/issues/772

**Comment by srkunze** [comment] 2015-02-16 18:17
Damn. I didn't find this one. Thanks, @Impyy 

Shall I close this issue now?

**Comment by aaannndddyyy** [comment] 2015-02-17 02:59
Yes

**Closed** 2015-02-17 13:45 UTC
