### ISSUE TITLE
add a method to easily find someone

### ISSUE THREAD

**Issue by dattaz** [irungentoo/toxcore#1258] opened 2015-02-15 21:58 UTC
I think user id with a hash is not very user-friendly
So a search method with nickname should be good.
You may have choice to add nickname or not to your hash id

**Comment by suhr** [comment] 2015-02-15 22:06
Duplicate of https://github.com/irungentoo/toxcore/issues/1222

**Comment by codedust** [comment] 2015-07-11 22:26
@irungentoo This issue can be closed as it's a duplicate.

**Closed** 2015-10-22 01:45 UTC
